version: "2"
services:
  server:
    image: jetbrains/teamcity-server:2017.1.4
    ports:
      - "8111:8111"
    volumes:
      - ./data:/data/teamcity_server/datadir
  agent1:
    build:
      context: .
      dockerfile: teamcity-agent.Dockerfile
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent1
    volumes:
#      - /opt/buildagent/work/:/opt/buildagent/work/
#      - /opt/buildagent/temp/:/opt/buildagent/temp/
#      - /opt/buildagent/system/:/opt/buildagent/system/
#      - /opt/buildagent/tools/:/opt/buildagent/tools/
#      - /opt/buildagent/plugins/:/opt/buildagent/plugins/
      - /var/run/docker.sock:/var/run/docker.sock
